## 01. Introduction to Pandas

In [2]:
import numpy as np
import pandas as pd

### Pandas Series

In [5]:
data = np.array(['r', 'a', 'f', 'a', 't'])
s = pd.Series(data)
s

0    r
1    a
2    f
3    a
4    t
dtype: object

### Pandas DataFrame

In [6]:
lst = ["rafat", "is", "a", "good", "boy"]
df = pd.DataFrame(lst)
df

       0
0  rafat
1     is
2      a
3   good
4    boy

### Load CSV File

In [8]:
df = pd.read_csv("data.csv")
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

### DF Info

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

### Count of Null Values

In [12]:
df.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

### Handling Missing Data

In [13]:
df = df.fillna(0)
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,0,5000000.0

### Selecting and Filtering Data

In [15]:
age = df[df['Age'] > 25]
age.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,0,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,0,12000000.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0

### Adding Columns

In [16]:
age['A+W'] = age['Age'] + age['Weight']
age.head()

C:\Users\rafat\AppData\Local\Temp\ipykernel_20504\2264615785.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  age['A+W'] = age['Age'] + age['Weight']

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,A+W
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0,232.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,0,5000000.0,260.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,0,12000000.0,269.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0,212.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0,247.0

### Grouping Data (GroupBy)

In [27]:
res = df.groupby('College')['Salary'].sum()
res

College
0                   478043881.0
Alabama               4265059.0
Arizona              43237322.0
Arizona State        15867882.0
Arkansas              8139540.0
                       ...
Western Michigan       845059.0
Wichita State          845059.0
Wisconsin             9872459.0
Wyoming               1155600.0
Xavier                1499187.0
Name: Salary, Length: 119, dtype: float64

## 02. Pandas DataFrame

In [55]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(data, columns = ['A', 'B', 'C'])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [34]:
data = { 
          'Name': ['Tom', 'nick', 'krish', 'jack'],
          'Age': [20, 21, 19, 18],
          'Marks': [20.5, 91.2, 67.7, 53.0]
       }

df = pd.DataFrame(data)
df

    Name  Age  Marks
0    Tom   20   20.5
1   nick   21   91.2
2  krish   19   67.7
3   jack   18   53.0

### Column Selection

In [31]:
df[['Name', 'Marks']]

    Name  Marks
0    Tom   20.5
1   nick   91.2
2  krish   67.7
3   jack   53.0

### Row Selection

In [35]:
person = df.loc[3]
person

Name     jack
Age        18
Marks    53.0
Name: 3, dtype: object

In [36]:
data = pd.read_csv("data.csv", index_col = "Name")

person = data.loc["Avery Bradley"]
person

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object

### Indexing a DataFrame

In [ ]:
data.iloc[3]

Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object

### isnull()

In [39]:
dict = {
          'First Score' : [100, 90, np.nan, 95],
          'Second Score' : [30, 45, 56, np.nan],
          'Third Score' : [np.nan, 40, 80, 98]
       }

df = pd.DataFrame(dict)
df.isnull()

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

### notnull()

In [40]:
df.notnull()

   First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

### Fill Missing Values

In [42]:
temp = df
temp.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [47]:
temp = df
temp.replace(np.nan, 1)

   First Score  Second Score  Third Score
0        100.0          30.0          1.0
1         90.0          45.0         40.0
2          1.0          56.0         80.0
3         95.0           1.0         98.0

In [48]:
temp = df
temp.interpolate()

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         92.5          56.0         80.0
3         95.0          56.0         98.0

### Drop Missing Values

In [49]:
temp = df
temp.dropna()

   First Score  Second Score  Third Score
1         90.0          45.0         40.0

### Iterating Over Rows

In [51]:
for i, j in df.iterrows():
  print(i, j)
  print()

0 First Score     100.0
Second Score     30.0
Third Score       NaN
Name: 0, dtype: float64

1 First Score     90.0
Second Score    45.0
Third Score     40.0
Name: 1, dtype: float64

2 First Score      NaN
Second Score    56.0
Third Score     80.0
Name: 2, dtype: float64

3 First Score     95.0
Second Score     NaN
Third Score     98.0
Name: 3, dtype: float64

### Iterating Over Columns

In [53]:
for i in list(temp):
  print(df[i][1])

90.0
45.0
40.0