## 01 - Introduction To Pandas
---
Importing Modules

In [2]:
import pandas as pd 
import numpy as np

---
### Pandas Series

In [ ]:
data = np.array(['r', 'a', 'f', 'a', 't'])   
ser = pd.Series(data)
print(ser)

0    r
1    a
2    f
3    a
4    t
dtype: object

---
### Pandas DataFrame

In [5]:
lst = ['Rafat', 'Alam', 'is', 'a', 'good', 'boy'] 
df = pd.DataFrame(lst) 
print(df)

       0
0  Rafat
1   Alam
2     is
3      a
4   good
5    boy

---
### Displaying Data

In [6]:
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}

df = pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

---
### Naming Columns

In [4]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(data, columns = ['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

---
### Displaying Selected Columns

In [57]:
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

df = pd.DataFrame(data)
print(df["Name"])
print("----")
print(df[['Name', 'Qualification', 'Address']])

0       Jai
1    Princi
2    Gaurav
3      Anuj
Name: Name, dtype: object
----
     Name Qualification    Address
0     Jai           Msc      Delhi
1  Princi            MA     Kanpur
2  Gaurav           MCA  Allahabad
3    Anuj           Phd    Kannauj

---
### Displaying Selected Rows of Selected Columns

In [37]:
data = {'A': [1, 2, 3, 4, 5],
        'B': [1, 2, 3, 4, 5],
        'C': [1, 2, 3, 4, 5],
        'D': [1, 2, 3, 4, 5],
        'E': [1, 2, 3, 4, 5],
        'F': [1, 2, 3, 4, 5],
        'G': [1, 2, 3, 4, 5]}

df = pd.DataFrame(data)
print(df.loc[0:2, ['A', 'B', 'C']])
print(df.loc[1:3, ['A', 'C', 'E']])

   A  B  C
0  1  1  1
1  2  2  2
2  3  3  3
   A  C  E
1  2  2  2
2  3  3  3
3  4  4  4

---
### Displaying Selected Rows using Values

In [41]:
data = pd.read_csv("nba.csv", index_col ="Name")

person = data.loc["Avery Bradley"]
print(person)

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object

---
### Displaying Selected Rows and Colums using Values

In [53]:
data = pd.read_csv("nba.csv", index_col = "Name")

person = data.loc[["Avery Bradley", "R.J. Hunter"], ['Team', 'Number', 'Position']]
print(person)

                         Team  Number Position
Name
Avery Bradley  Boston Celtics     0.0       PG
R.J. Hunter    Boston Celtics    28.0       SG

---
### Start / Stop / Step of Index

In [16]:
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df)
print("Starting Index :", df.index.start)
print("Stoping Index :", df.index.stop)
print("Steps :", df.index.step)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000
Starting Index : 0
Stoping Index : 5
Steps : 1

---
### Setting our own Index

In [27]:
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
df = df.set_index('Name')
print(df)

row = df.loc['Alice']
print(row)

         Age  Gender  Salary
Name
John      25    Male   50000
Alice     30  Female   55000
Bob       22    Male   40000
Eve       35  Female   70000
Charlie   28    Male   48000
Age           30
Gender    Female
Salary     55000
Name: Alice, dtype: object

---
### Selecting Rows on Basis of Conditions

In [38]:
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df[df['Age'] > 25])

      Name  Age  Gender  Salary
1    Alice   30  Female   55000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

---
### Selecting Columns by Index

In [64]:
data = pd.read_csv("nba.csv", index_col = "Name")

print(data.iloc[3])

Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object

---
### isNull()

In [62]:
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}

df = pd.DataFrame(dict)
df.isnull()

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

---
### fillna(val)

In [63]:
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}

df = pd.DataFrame(dict)
df.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

---
### dropna()

In [65]:

dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, 65]}
 
df = pd.DataFrame(dict)
df.dropna()

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

---
### Iterating Rows of Table

In [ ]:
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}
 
df = pd.DataFrame(dict)

for i, j in df.iterrows():
  print(i, j)
  print()

0 90

1 40

2 80

3 98

---
### Head of Data

In [ ]:
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df.head(3))       # Default : 5

    Name  Age  Gender  Salary
0   John   25    Male   50000
1  Alice   30  Female   55000
2    Bob   22    Male   40000